# Generated by Django 5.1.1 on 2024-10-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
